[versions]
core-ktx = "1.7.0"
fragment-Ktx = "1.5.5"
viewmodel-Ktx= "2.6.0-alpha03"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
fragment-Ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-Ktx" }
viewmodel-Ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewmodel-Ktx" }



